.PS 5
circle "circle" "a new line" "i am shovon" rad 1 at (-2,0)
A: ellipse "ellipse" ht 1 wid 1 at (0,0)
box "box" ht 1 wid 1 at (2,0)
box "box" ht 3 wid 1 at (2,-3)
B: ellipse "ellipse" ht 1 wid 2 at (-3,-3)

line from A.w to B.n
arc from 2nd last ellipse.s to last box.sw
arrow from 2nd last box.s to last box.n
.PE

"essentially making ellipse look like circle."

line "line"
spline "spline"
arrow "arrow"
arc "arc"
